"""M12 hearable tests + the first audio-in/response-out loop.

Outputs (whitebox/runs/m12/):
  hear_committed.wav  - original drum audio + HEU-committed clicks
  hear_baseline.wav   - original + flux/peak-pick baseline clicks
  callresponse.wav    - 8 bars original audio, then 8 bars of
                        clicks GENERATED by the clocked GLM seeded
                        ONLY from the audio-committed events.
Also prints F1/fragmentation for HEU vs the standard peak-pick
baseline (the legitimacy comparison).

python3 -m whitebox.m12_hear
"""

import csv
import pathlib
import sys
import wave

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(pathlib.Path.home() / 'coding' /
                       'heu-replication'))

from whitebox.m12_frontend import (GMD, OUT, SR, audio_envelope,    # noqa
                                   commit, midi_onsets, score)

BIN = 0.020


def peak_pick(flux, win=100, k=1.5, minsep=30):
    """Standard adaptive-threshold peak picking on onset flux."""
    n = len(flux)
    events = []
    last = -1e9
    for t in range(1, n - 1):
        lo = max(0, t - win)
        thr = flux[lo:t + 1].mean() + k * flux[lo:t + 1].std()
        if flux[t] >= thr and flux[t] >= flux[t-1] \
                and flux[t] >= flux[t+1] and t - last >= minsep:
            events.append(t)
            last = t
    return np.array(events, float)


def load_wav(path):
    w = wave.open(str(path))
    x = np.frombuffer(w.readframes(w.getnframes()), np.int16
                      ).astype(np.float64)
    if w.getnchannels() == 2:
        x = x.reshape(-1, 2).mean(1)
    return x / 32768.0


def save_wav(path, x):
    x = np.clip(x, -1, 1)
    w = wave.open(str(path), 'w')
    w.setnchannels(1)
    w.setsampwidth(2)
    w.setframerate(SR)
    w.writeframes((x * 32767).astype(np.int16).tobytes())
    w.close()


def click_track(events_ms, total_s, freq=2000):
    x = np.zeros(int(total_s * SR))
    t = np.arange(int(0.02 * SR))
    tick = np.sin(2 * np.pi * freq * t / SR) * np.exp(-t / (0.004 * SR))
    for e in events_ms:
        i = int(e / 1000 * SR)
        if i + len(tick) < len(x):
            x[i:i + len(tick)] += tick
    return 0.7 * x


def main():
    rows = [r for r in csv.DictReader(open(GMD / 'info.csv'))
            if r['beat_type'] == 'beat'
            and r['time_signature'] == '4-4'
            and 20 < float(r['duration']) < 60]
    rng = np.random.default_rng(0)
    rng.shuffle(rows)

    # legitimacy: HEU vs peak-pick over the 12-file set
    heu_s, pk_s = [], []
    for r in rows[:12]:
        p = GMD / r['midi_filename']
        truth = midi_onsets(p)
        flux = audio_envelope(p)
        sp, _ = commit(flux * 1.5, [[0, 0, 0, 0]])
        pk = peak_pick(flux)
        heu_s.append(score(sp, truth, 40))
        pk_s.append(score(pk, truth, 40))
    h, q = np.array(heu_s), np.array(pk_s)
    print(f'HEU commit   : F1 {h[:,0].mean():.3f}  frag {h[:,3].mean():.2f}')
    print(f'flux+peakpick: F1 {q[:,0].mean():.3f}  frag {q[:,3].mean():.2f}',
          flush=True)

    # hearable renders on one groove
    r = rows[0]
    p = GMD / r['midi_filename']
    bpm = float(r['bpm'])
    audio = load_wav(OUT / (p.stem + '.wav'))
    total_s = len(audio) / SR
    flux = audio_envelope(p)
    sp, _ = commit(flux * 1.5, [[0, 0, 0, 0]])
    pk = peak_pick(flux)
    save_wav(OUT / 'hear_committed.wav',
             0.6 * audio + click_track(sp, total_s))
    save_wav(OUT / 'hear_baseline.wav',
             0.6 * audio + click_track(pk, total_s))
    print(f'renders: hear_committed.wav / hear_baseline.wav '
          f'({p.stem}, {bpm:.0f}bpm)', flush=True)

    # call-and-response: fit clock+traces GLM on GMD single-channel
    import torch
    from scipy.signal import lfilter
    data = np.load('whitebox/runs/rhythm/gmd.npz', allow_pickle=True)
    HL = [0.02 * 2 ** i for i in range(10)]

    def feats(x):
        cols = []
        for hl in HL:
            lam = 0.5 ** (BIN / hl)
            c = lfilter([1 - lam], [1, -lam], x.astype(np.float64))
            cols.append(np.concatenate([[0.0], c[:-1]]))
        return np.stack(cols, 1).astype(np.float32)

    def clockf(n, bpm_, phase=0.0):
        tt = np.arange(n) * BIN
        s16 = (4 * tt * bpm_ / 60.0 + phase) % 1.0
        idx = np.minimum((s16 * 16).astype(int), 15)
        C = np.zeros((n, 16), np.float32)
        C[np.arange(n), idx] = 1.0
        return C

    rows_all = [q2 for q2 in csv.DictReader(open(GMD / 'info.csv'))]
    bpm_map = {}
    i = 0
    import mido
    for q2 in rows_all:
        if q2['split'] != 'train':
            continue
        try:
            mid = mido.MidiFile(GMD / q2['midi_filename'])
        except Exception:
            continue
        if sum(1 for m in mid if m.type == 'note_on'
               and m.velocity > 0) < 8:
            continue
        bpm_map[i] = float(q2['bpm'])
        i += 1
    Xs, Ys = [], []
    for j, x in enumerate(data['train']):
        b = bpm_map.get(j, 120.0)
        Xs.append(np.concatenate([clockf(len(x), b), feats(x)], 1))
        Ys.append(x.astype(np.float32))
    Xtr = np.concatenate(Xs)
    Ytr = np.concatenate(Ys)
    r0 = float(np.clip(Ytr.mean(), 1e-4, 1))
    torch.manual_seed(0)
    net = torch.nn.Linear(26, 1)
    with torch.no_grad():
        net.bias.fill_(float(np.log(r0 / (1 - r0))))
    mu, sd = Xtr.mean(0), Xtr.std(0) + 1e-6
    Xt = torch.from_numpy((Xtr - mu) / sd)
    Yt = torch.from_numpy(Ytr[:, None])
    opt = torch.optim.Adam(net.parameters(), lr=3e-3)
    for ep in range(6):
        perm = torch.randperm(len(Xt))
        for k2 in range(0, len(Xt), 65536):
            ii = perm[k2:k2+65536]
            loss = torch.nn.functional.binary_cross_entropy_with_logits(
                net(Xt[ii]), Yt[ii])
            opt.zero_grad(); loss.backward(); opt.step()

    # seed from AUDIO-committed events (8 bars), generate 8 bars
    bar_s = 4 * 60 / bpm
    seed_s = 8 * bar_s
    seed_bins = int(seed_s / BIN)
    raster = np.zeros(seed_bins, np.uint8)
    for e in sp:
        b2 = int(e / 1000 / BIN)
        if b2 < seed_bins:
            raster[b2] = 1
    # trace state warmup
    lam = np.array([0.5 ** (BIN / hl) for hl in HL])
    st = np.zeros(len(HL))
    for v in raster:
        st = lam * st + (1 - lam) * v
    gen_bins = seed_bins
    gen = np.zeros(gen_bins, np.uint8)
    rng2 = np.random.default_rng(4)
    for t in range(gen_bins):
        tt = (seed_bins + t) * BIN
        s16 = (4 * tt * bpm / 60.0) % 1.0
        C = np.zeros(16, np.float32)
        C[min(15, int(s16 * 16))] = 1.0
        f = np.concatenate([C, st.astype(np.float32)])
        f = (f - mu) / sd
        with torch.no_grad():
            pgen = float(torch.sigmoid(net(
                torch.from_numpy(f[None]))))
        v = int(rng2.random() < pgen)
        gen[t] = v
        st = lam * st + (1 - lam) * v
    gen_ms = (np.where(gen)[0] + seed_bins) * BIN * 1000
    out = np.zeros(int((seed_s * 2 + 1) * SR))
    seg = audio[:int(seed_s * SR)]
    out[:len(seg)] += 0.6 * seg
    ct = click_track(gen_ms, seed_s * 2 + 1)
    out[:len(ct)] += ct
    save_wav(OUT / 'callresponse.wav', out)
    print(f'callresponse.wav: 8 bars audio in -> 8 bars generated '
          f'({gen.sum()} events, seed had {raster.sum()})', flush=True)


if __name__ == '__main__':
    main()
